server:
  port: 7090
spring:
  application:
    name: sharding-db
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: site.muzhi.common.entity