spring:
  shardingsphere:
    datasource:
      names: master
      # names中定义的数据源名称
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sdb-0?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: root
    sharding:
      tables:
        # 逻辑表
        user:
          # 主键生成算法
          key-generator:
            column: id
            type: SNOWFLAKE
          # 分片表
          actual-data-nodes: master.user_${0..2}
          # 自定义分片算法
          table-strategy:
            standard:
              # 分片依据(表中的属性字段)
              sharding-column: id
              # 自定义分片算法
              precise-algorithm-class-name: site.muzhi.learn.algorithm.UserTablePreciseShardingAlgorithmImpl
    # 显示sql
    props:
      sql:
        show: true